/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWorkspacesRouteImport } from './routes/_admin/workspaces'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminSupportRouteImport } from './routes/_admin/support'
import { Route as AdminFeatureFlagsRouteImport } from './routes/_admin/feature-flags'
import { Route as AdminEventsRouteImport } from './routes/_admin/events'
import { Route as AdminErrorsRouteImport } from './routes/_admin/errors'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminClockStationsRouteImport } from './routes/_admin/clock-stations'
import { Route as AdminBillingRouteImport } from './routes/_admin/billing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClockStationsRoute = AdminClockStationsRouteImport.update({
  id: '/clock-stations',
  path: '/clock-stations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AdminBillingRoute
  '/clock-stations': typeof AdminClockStationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/errors': typeof AdminErrorsRoute
  '/events': typeof AdminEventsRoute
  '/feature-flags': typeof AdminFeatureFlagsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
  '/workspaces': typeof AdminWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AdminBillingRoute
  '/clock-stations': typeof AdminClockStationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/errors': typeof AdminErrorsRoute
  '/events': typeof AdminEventsRoute
  '/feature-flags': typeof AdminFeatureFlagsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
  '/workspaces': typeof AdminWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/billing': typeof AdminBillingRoute
  '/_admin/clock-stations': typeof AdminClockStationsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/errors': typeof AdminErrorsRoute
  '/_admin/events': typeof AdminEventsRoute
  '/_admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/_admin/support': typeof AdminSupportRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/workspaces': typeof AdminWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/clock-stations'
    | '/dashboard'
    | '/errors'
    | '/events'
    | '/feature-flags'
    | '/support'
    | '/users'
    | '/workspaces'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/billing'
    | '/clock-stations'
    | '/dashboard'
    | '/errors'
    | '/events'
    | '/feature-flags'
    | '/support'
    | '/users'
    | '/workspaces'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/billing'
    | '/_admin/clock-stations'
    | '/_admin/dashboard'
    | '/_admin/errors'
    | '/_admin/events'
    | '/_admin/feature-flags'
    | '/_admin/support'
    | '/_admin/users'
    | '/_admin/workspaces'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/workspaces': {
      id: '/_admin/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support': {
      id: '/_admin/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/feature-flags': {
      id: '/_admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events': {
      id: '/_admin/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/errors': {
      id: '/_admin/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clock-stations': {
      id: '/_admin/clock-stations'
      path: '/clock-stations'
      fullPath: '/clock-stations'
      preLoaderRoute: typeof AdminClockStationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/billing': {
      id: '/_admin/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminClockStationsRoute: typeof AdminClockStationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminClockStationsRoute: AdminClockStationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
