const NTAG_PUBLIC_ID_PREFIX = "clk_"
const NTAG_PUBLIC_ID_RANDOM_BYTES = 16
const NTAG_PUBLIC_ID_LENGTH =
  NTAG_PUBLIC_ID_PREFIX.length + NTAG_PUBLIC_ID_RANDOM_BYTES * 2
const NTAG_TAG_OFFSET_PLACEHOLDER = `${NTAG_PUBLIC_ID_PREFIX}${"0".repeat(
  NTAG_PUBLIC_ID_RANDOM_BYTES * 2
)}`
const NTAG_PICC_HEX_LENGTH = 32
const NTAG_CMAC_HEX_LENGTH = 16
const NTAG_PICC_OFFSET_PLACEHOLDER = "0".repeat(NTAG_PICC_HEX_LENGTH)
const NTAG_CMAC_OFFSET_PLACEHOLDER = "0".repeat(NTAG_CMAC_HEX_LENGTH)

export {
  NTAG_CMAC_HEX_LENGTH,
  NTAG_CMAC_OFFSET_PLACEHOLDER,
  NTAG_PICC_HEX_LENGTH,
  NTAG_PICC_OFFSET_PLACEHOLDER,
  NTAG_PUBLIC_ID_LENGTH,
  NTAG_PUBLIC_ID_PREFIX,
  NTAG_PUBLIC_ID_RANDOM_BYTES,
  NTAG_TAG_OFFSET_PLACEHOLDER,
}
