/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as HelpSplatRouteImport } from './routes/help/$'
import { Route as FeaturesTimesheetsRouteImport } from './routes/features/timesheets'
import { Route as FeaturesTimeTrackingRouteImport } from './routes/features/time-tracking'
import { Route as FeaturesRotaPlanningRouteImport } from './routes/features/rota-planning'
import { Route as ClockTokenRouteImport } from './routes/clock/$token'
import { Route as AdminClockTagsRouteImport } from './routes/admin/clock-tags'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as AuthedVerifiedRouteRouteImport } from './routes/_authed/_verified/route'
import { Route as ApiSupportThreadRouteImport } from './routes/api/support/thread'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiBillingReconcileRouteImport } from './routes/api/billing/reconcile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminTelemetryEventRouteImport } from './routes/api/admin-telemetry/event'
import { Route as ApiAdminTelemetryErrorRouteImport } from './routes/api/admin-telemetry/error'
import { Route as AuthedVerifiedDashboardRouteImport } from './routes/_authed/_verified/dashboard'
import { Route as AuthedVerifiedAccountRouteImport } from './routes/_authed/_verified/account'
import { Route as AuthedVerifiedWIndexRouteImport } from './routes/_authed/_verified/w/index'
import { Route as ApiAuthStripeWebhookRouteImport } from './routes/api/auth/stripe/webhook'
import { Route as AuthedVerifiedWSplatRouteImport } from './routes/_authed/_verified/w/$'
import { Route as AuthedVerifiedOnboardingSetupRouteImport } from './routes/_authed/_verified/onboarding/setup'
import { Route as AuthedVerifiedOnboardingOrgRouteImport } from './routes/_authed/_verified/onboarding/org'
import { Route as AuthedVerifiedOnboardingLocationRouteImport } from './routes/_authed/_verified/onboarding/location'
import { Route as AuthedVerifiedOnboardingJoinRouteImport } from './routes/_authed/_verified/onboarding/join'
import { Route as AuthedVerifiedOnboardingInviteRouteImport } from './routes/_authed/_verified/onboarding/invite'
import { Route as AuthedVerifiedBillingSuccessRouteImport } from './routes/_authed/_verified/billing/success'
import { Route as AuthedVerifiedBillingExpiredRouteImport } from './routes/_authed/_verified/billing/expired'
import { Route as AuthedVerifiedAppWorkspaceSlugRouteRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/route'
import { Route as AuthedVerifiedAppWorkspaceSlugIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/index'
import { Route as AuthedVerifiedAppWorkspaceSlugTimesheetsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/timesheets'
import { Route as AuthedVerifiedAppWorkspaceSlugTimeClockRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/time-clock'
import { Route as AuthedVerifiedAppWorkspaceSlugShiftSwapsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/shift-swaps'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings'
import { Route as AuthedVerifiedAppWorkspaceSlugDashboardRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/dashboard'
import { Route as AuthedVerifiedAppWorkspaceSlugAnnouncementsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/announcements'
import { Route as AuthedVerifiedAppWorkspaceSlugAccountRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/account'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/index'
import { Route as AuthedVerifiedAppWorkspaceSlugRotaIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/rota/index'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/team'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/rota'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsLocationsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/locations'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsGeneralRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/general'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/connections'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/company'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsClockingRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/clocking'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsBillingRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/billing'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/team/index'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/rota/index'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/company/index'
import { Route as AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRouteImport } from './routes/_authed/_verified/o/$orgSlug/rota/$locationSlug/$rotaId'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/team/groups'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/rota/zones'
import { Route as AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/settings/company/$employeeId'
import { Route as AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId'
import { Route as AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/index'
import { Route as AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRouteImport } from './routes/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSplatRoute = HelpSplatRouteImport.update({
  id: '/help/$',
  path: '/help/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesTimesheetsRoute = FeaturesTimesheetsRouteImport.update({
  id: '/features/timesheets',
  path: '/features/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesTimeTrackingRoute = FeaturesTimeTrackingRouteImport.update({
  id: '/features/time-tracking',
  path: '/features/time-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRotaPlanningRoute = FeaturesRotaPlanningRouteImport.update({
  id: '/features/rota-planning',
  path: '/features/rota-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockTokenRoute = ClockTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ClockRoute,
} as any)
const AdminClockTagsRoute = AdminClockTagsRouteImport.update({
  id: '/admin/clock-tags',
  path: '/admin/clock-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedVerifiedRouteRoute = AuthedVerifiedRouteRouteImport.update({
  id: '/_verified',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiSupportThreadRoute = ApiSupportThreadRouteImport.update({
  id: '/api/support/thread',
  path: '/api/support/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingReconcileRoute = ApiBillingReconcileRouteImport.update({
  id: '/api/billing/reconcile',
  path: '/api/billing/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTelemetryEventRoute = ApiAdminTelemetryEventRouteImport.update({
  id: '/api/admin-telemetry/event',
  path: '/api/admin-telemetry/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTelemetryErrorRoute = ApiAdminTelemetryErrorRouteImport.update({
  id: '/api/admin-telemetry/error',
  path: '/api/admin-telemetry/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVerifiedDashboardRoute = AuthedVerifiedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedVerifiedRouteRoute,
} as any)
const AuthedVerifiedAccountRoute = AuthedVerifiedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedVerifiedRouteRoute,
} as any)
const AuthedVerifiedWIndexRoute = AuthedVerifiedWIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => AuthedVerifiedRouteRoute,
} as any)
const ApiAuthStripeWebhookRoute = ApiAuthStripeWebhookRouteImport.update({
  id: '/api/auth/stripe/webhook',
  path: '/api/auth/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVerifiedWSplatRoute = AuthedVerifiedWSplatRouteImport.update({
  id: '/w/$',
  path: '/w/$',
  getParentRoute: () => AuthedVerifiedRouteRoute,
} as any)
const AuthedVerifiedOnboardingSetupRoute =
  AuthedVerifiedOnboardingSetupRouteImport.update({
    id: '/onboarding/setup',
    path: '/onboarding/setup',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedOnboardingOrgRoute =
  AuthedVerifiedOnboardingOrgRouteImport.update({
    id: '/onboarding/org',
    path: '/onboarding/org',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedOnboardingLocationRoute =
  AuthedVerifiedOnboardingLocationRouteImport.update({
    id: '/onboarding/location',
    path: '/onboarding/location',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedOnboardingJoinRoute =
  AuthedVerifiedOnboardingJoinRouteImport.update({
    id: '/onboarding/join',
    path: '/onboarding/join',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedOnboardingInviteRoute =
  AuthedVerifiedOnboardingInviteRouteImport.update({
    id: '/onboarding/invite',
    path: '/onboarding/invite',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedBillingSuccessRoute =
  AuthedVerifiedBillingSuccessRouteImport.update({
    id: '/billing/success',
    path: '/billing/success',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedBillingExpiredRoute =
  AuthedVerifiedBillingExpiredRouteImport.update({
    id: '/billing/expired',
    path: '/billing/expired',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugRouteRoute =
  AuthedVerifiedAppWorkspaceSlugRouteRouteImport.update({
    id: '/app/$workspaceSlug',
    path: '/app/$workspaceSlug',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugIndexRoute =
  AuthedVerifiedAppWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugTimesheetsRoute =
  AuthedVerifiedAppWorkspaceSlugTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugTimeClockRoute =
  AuthedVerifiedAppWorkspaceSlugTimeClockRouteImport.update({
    id: '/time-clock',
    path: '/time-clock',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute =
  AuthedVerifiedAppWorkspaceSlugShiftSwapsRouteImport.update({
    id: '/shift-swaps',
    path: '/shift-swaps',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugDashboardRoute =
  AuthedVerifiedAppWorkspaceSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute =
  AuthedVerifiedAppWorkspaceSlugAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugAccountRoute =
  AuthedVerifiedAppWorkspaceSlugAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugRotaIndexRoute =
  AuthedVerifiedAppWorkspaceSlugRotaIndexRouteImport.update({
    id: '/rota/',
    path: '/rota/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteImport.update({
    id: '/rota',
    path: '/rota',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsClockingRouteImport.update({
    id: '/clocking',
    path: '/clocking',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute,
  } as any)
const AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute =
  AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRouteImport.update({
    id: '/o/$orgSlug/rota/$locationSlug/$rotaId',
    path: '/o/$orgSlug/rota/$locationSlug/$rotaId',
    getParentRoute: () => AuthedVerifiedRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRouteImport.update({
    id: '/zones',
    path: '/zones',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute =
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute =
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteImport.update({
    id: '/rota/$locationSlug/$rotaId',
    path: '/rota/$locationSlug/$rotaId',
    getParentRoute: () => AuthedVerifiedAppWorkspaceSlugRouteRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute =
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute,
  } as any)
const AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute =
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () =>
      AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock': typeof ClockRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/clock-tags': typeof AdminClockTagsRoute
  '/clock/$token': typeof ClockTokenRoute
  '/features/rota-planning': typeof FeaturesRotaPlanningRoute
  '/features/time-tracking': typeof FeaturesTimeTrackingRoute
  '/features/timesheets': typeof FeaturesTimesheetsRoute
  '/help/$': typeof HelpSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/help/': typeof HelpIndexRoute
  '/account': typeof AuthedVerifiedAccountRoute
  '/dashboard': typeof AuthedVerifiedDashboardRoute
  '/api/admin-telemetry/error': typeof ApiAdminTelemetryErrorRoute
  '/api/admin-telemetry/event': typeof ApiAdminTelemetryEventRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/support/thread': typeof ApiSupportThreadRoute
  '/app/$workspaceSlug': typeof AuthedVerifiedAppWorkspaceSlugRouteRouteWithChildren
  '/billing/expired': typeof AuthedVerifiedBillingExpiredRoute
  '/billing/success': typeof AuthedVerifiedBillingSuccessRoute
  '/onboarding/invite': typeof AuthedVerifiedOnboardingInviteRoute
  '/onboarding/join': typeof AuthedVerifiedOnboardingJoinRoute
  '/onboarding/location': typeof AuthedVerifiedOnboardingLocationRoute
  '/onboarding/org': typeof AuthedVerifiedOnboardingOrgRoute
  '/onboarding/setup': typeof AuthedVerifiedOnboardingSetupRoute
  '/w/$': typeof AuthedVerifiedWSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/w/': typeof AuthedVerifiedWIndexRoute
  '/app/$workspaceSlug/account': typeof AuthedVerifiedAppWorkspaceSlugAccountRoute
  '/app/$workspaceSlug/announcements': typeof AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute
  '/app/$workspaceSlug/dashboard': typeof AuthedVerifiedAppWorkspaceSlugDashboardRoute
  '/app/$workspaceSlug/settings': typeof AuthedVerifiedAppWorkspaceSlugSettingsRouteWithChildren
  '/app/$workspaceSlug/shift-swaps': typeof AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute
  '/app/$workspaceSlug/time-clock': typeof AuthedVerifiedAppWorkspaceSlugTimeClockRoute
  '/app/$workspaceSlug/timesheets': typeof AuthedVerifiedAppWorkspaceSlugTimesheetsRoute
  '/app/$workspaceSlug/': typeof AuthedVerifiedAppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/settings/billing': typeof AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute
  '/app/$workspaceSlug/settings/clocking': typeof AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute
  '/app/$workspaceSlug/settings/company': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteWithChildren
  '/app/$workspaceSlug/settings/connections': typeof AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute
  '/app/$workspaceSlug/settings/general': typeof AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute
  '/app/$workspaceSlug/settings/locations': typeof AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute
  '/app/$workspaceSlug/settings/rota': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteWithChildren
  '/app/$workspaceSlug/settings/team': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteWithChildren
  '/app/$workspaceSlug/rota/': typeof AuthedVerifiedAppWorkspaceSlugRotaIndexRoute
  '/app/$workspaceSlug/settings/': typeof AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute
  '/app/$workspaceSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteWithChildren
  '/app/$workspaceSlug/settings/company/$employeeId': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute
  '/app/$workspaceSlug/settings/rota/zones': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute
  '/app/$workspaceSlug/settings/team/groups': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute
  '/o/$orgSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute
  '/app/$workspaceSlug/settings/company/': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute
  '/app/$workspaceSlug/settings/rota/': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute
  '/app/$workspaceSlug/settings/team/': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute
  '/app/$workspaceSlug/rota/$locationSlug/$rotaId/view': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute
  '/app/$workspaceSlug/rota/$locationSlug/$rotaId/': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock': typeof ClockRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/clock-tags': typeof AdminClockTagsRoute
  '/clock/$token': typeof ClockTokenRoute
  '/features/rota-planning': typeof FeaturesRotaPlanningRoute
  '/features/time-tracking': typeof FeaturesTimeTrackingRoute
  '/features/timesheets': typeof FeaturesTimesheetsRoute
  '/help/$': typeof HelpSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/help': typeof HelpIndexRoute
  '/account': typeof AuthedVerifiedAccountRoute
  '/dashboard': typeof AuthedVerifiedDashboardRoute
  '/api/admin-telemetry/error': typeof ApiAdminTelemetryErrorRoute
  '/api/admin-telemetry/event': typeof ApiAdminTelemetryEventRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/support/thread': typeof ApiSupportThreadRoute
  '/billing/expired': typeof AuthedVerifiedBillingExpiredRoute
  '/billing/success': typeof AuthedVerifiedBillingSuccessRoute
  '/onboarding/invite': typeof AuthedVerifiedOnboardingInviteRoute
  '/onboarding/join': typeof AuthedVerifiedOnboardingJoinRoute
  '/onboarding/location': typeof AuthedVerifiedOnboardingLocationRoute
  '/onboarding/org': typeof AuthedVerifiedOnboardingOrgRoute
  '/onboarding/setup': typeof AuthedVerifiedOnboardingSetupRoute
  '/w/$': typeof AuthedVerifiedWSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/w': typeof AuthedVerifiedWIndexRoute
  '/app/$workspaceSlug/account': typeof AuthedVerifiedAppWorkspaceSlugAccountRoute
  '/app/$workspaceSlug/announcements': typeof AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute
  '/app/$workspaceSlug/dashboard': typeof AuthedVerifiedAppWorkspaceSlugDashboardRoute
  '/app/$workspaceSlug/shift-swaps': typeof AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute
  '/app/$workspaceSlug/time-clock': typeof AuthedVerifiedAppWorkspaceSlugTimeClockRoute
  '/app/$workspaceSlug/timesheets': typeof AuthedVerifiedAppWorkspaceSlugTimesheetsRoute
  '/app/$workspaceSlug': typeof AuthedVerifiedAppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/settings/billing': typeof AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute
  '/app/$workspaceSlug/settings/clocking': typeof AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute
  '/app/$workspaceSlug/settings/connections': typeof AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute
  '/app/$workspaceSlug/settings/general': typeof AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute
  '/app/$workspaceSlug/settings/locations': typeof AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute
  '/app/$workspaceSlug/rota': typeof AuthedVerifiedAppWorkspaceSlugRotaIndexRoute
  '/app/$workspaceSlug/settings': typeof AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute
  '/app/$workspaceSlug/settings/company/$employeeId': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute
  '/app/$workspaceSlug/settings/rota/zones': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute
  '/app/$workspaceSlug/settings/team/groups': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute
  '/o/$orgSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute
  '/app/$workspaceSlug/settings/company': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute
  '/app/$workspaceSlug/settings/rota': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute
  '/app/$workspaceSlug/settings/team': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute
  '/app/$workspaceSlug/rota/$locationSlug/$rotaId/view': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute
  '/app/$workspaceSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/clock': typeof ClockRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/_verified': typeof AuthedVerifiedRouteRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/clock-tags': typeof AdminClockTagsRoute
  '/clock/$token': typeof ClockTokenRoute
  '/features/rota-planning': typeof FeaturesRotaPlanningRoute
  '/features/time-tracking': typeof FeaturesTimeTrackingRoute
  '/features/timesheets': typeof FeaturesTimesheetsRoute
  '/help/$': typeof HelpSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/help/': typeof HelpIndexRoute
  '/_authed/_verified/account': typeof AuthedVerifiedAccountRoute
  '/_authed/_verified/dashboard': typeof AuthedVerifiedDashboardRoute
  '/api/admin-telemetry/error': typeof ApiAdminTelemetryErrorRoute
  '/api/admin-telemetry/event': typeof ApiAdminTelemetryEventRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/support/thread': typeof ApiSupportThreadRoute
  '/_authed/_verified/app/$workspaceSlug': typeof AuthedVerifiedAppWorkspaceSlugRouteRouteWithChildren
  '/_authed/_verified/billing/expired': typeof AuthedVerifiedBillingExpiredRoute
  '/_authed/_verified/billing/success': typeof AuthedVerifiedBillingSuccessRoute
  '/_authed/_verified/onboarding/invite': typeof AuthedVerifiedOnboardingInviteRoute
  '/_authed/_verified/onboarding/join': typeof AuthedVerifiedOnboardingJoinRoute
  '/_authed/_verified/onboarding/location': typeof AuthedVerifiedOnboardingLocationRoute
  '/_authed/_verified/onboarding/org': typeof AuthedVerifiedOnboardingOrgRoute
  '/_authed/_verified/onboarding/setup': typeof AuthedVerifiedOnboardingSetupRoute
  '/_authed/_verified/w/$': typeof AuthedVerifiedWSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/_authed/_verified/w/': typeof AuthedVerifiedWIndexRoute
  '/_authed/_verified/app/$workspaceSlug/account': typeof AuthedVerifiedAppWorkspaceSlugAccountRoute
  '/_authed/_verified/app/$workspaceSlug/announcements': typeof AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute
  '/_authed/_verified/app/$workspaceSlug/dashboard': typeof AuthedVerifiedAppWorkspaceSlugDashboardRoute
  '/_authed/_verified/app/$workspaceSlug/settings': typeof AuthedVerifiedAppWorkspaceSlugSettingsRouteWithChildren
  '/_authed/_verified/app/$workspaceSlug/shift-swaps': typeof AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute
  '/_authed/_verified/app/$workspaceSlug/time-clock': typeof AuthedVerifiedAppWorkspaceSlugTimeClockRoute
  '/_authed/_verified/app/$workspaceSlug/timesheets': typeof AuthedVerifiedAppWorkspaceSlugTimesheetsRoute
  '/_authed/_verified/app/$workspaceSlug/': typeof AuthedVerifiedAppWorkspaceSlugIndexRoute
  '/_authed/_verified/app/$workspaceSlug/settings/billing': typeof AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute
  '/_authed/_verified/app/$workspaceSlug/settings/clocking': typeof AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute
  '/_authed/_verified/app/$workspaceSlug/settings/company': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteWithChildren
  '/_authed/_verified/app/$workspaceSlug/settings/connections': typeof AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute
  '/_authed/_verified/app/$workspaceSlug/settings/general': typeof AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute
  '/_authed/_verified/app/$workspaceSlug/settings/locations': typeof AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute
  '/_authed/_verified/app/$workspaceSlug/settings/rota': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteWithChildren
  '/_authed/_verified/app/$workspaceSlug/settings/team': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteWithChildren
  '/_authed/_verified/app/$workspaceSlug/rota/': typeof AuthedVerifiedAppWorkspaceSlugRotaIndexRoute
  '/_authed/_verified/app/$workspaceSlug/settings/': typeof AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute
  '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteWithChildren
  '/_authed/_verified/app/$workspaceSlug/settings/company/$employeeId': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute
  '/_authed/_verified/app/$workspaceSlug/settings/rota/zones': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute
  '/_authed/_verified/app/$workspaceSlug/settings/team/groups': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute
  '/_authed/_verified/o/$orgSlug/rota/$locationSlug/$rotaId': typeof AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute
  '/_authed/_verified/app/$workspaceSlug/settings/company/': typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute
  '/_authed/_verified/app/$workspaceSlug/settings/rota/': typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute
  '/_authed/_verified/app/$workspaceSlug/settings/team/': typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute
  '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/view': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute
  '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/': typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clock'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/admin/clock-tags'
    | '/clock/$token'
    | '/features/rota-planning'
    | '/features/time-tracking'
    | '/features/timesheets'
    | '/help/$'
    | '/join/$token'
    | '/help/'
    | '/account'
    | '/dashboard'
    | '/api/admin-telemetry/error'
    | '/api/admin-telemetry/event'
    | '/api/auth/$'
    | '/api/billing/reconcile'
    | '/api/stripe/webhook'
    | '/api/support/thread'
    | '/app/$workspaceSlug'
    | '/billing/expired'
    | '/billing/success'
    | '/onboarding/invite'
    | '/onboarding/join'
    | '/onboarding/location'
    | '/onboarding/org'
    | '/onboarding/setup'
    | '/w/$'
    | '/api/auth/stripe/webhook'
    | '/w/'
    | '/app/$workspaceSlug/account'
    | '/app/$workspaceSlug/announcements'
    | '/app/$workspaceSlug/dashboard'
    | '/app/$workspaceSlug/settings'
    | '/app/$workspaceSlug/shift-swaps'
    | '/app/$workspaceSlug/time-clock'
    | '/app/$workspaceSlug/timesheets'
    | '/app/$workspaceSlug/'
    | '/app/$workspaceSlug/settings/billing'
    | '/app/$workspaceSlug/settings/clocking'
    | '/app/$workspaceSlug/settings/company'
    | '/app/$workspaceSlug/settings/connections'
    | '/app/$workspaceSlug/settings/general'
    | '/app/$workspaceSlug/settings/locations'
    | '/app/$workspaceSlug/settings/rota'
    | '/app/$workspaceSlug/settings/team'
    | '/app/$workspaceSlug/rota/'
    | '/app/$workspaceSlug/settings/'
    | '/app/$workspaceSlug/rota/$locationSlug/$rotaId'
    | '/app/$workspaceSlug/settings/company/$employeeId'
    | '/app/$workspaceSlug/settings/rota/zones'
    | '/app/$workspaceSlug/settings/team/groups'
    | '/o/$orgSlug/rota/$locationSlug/$rotaId'
    | '/app/$workspaceSlug/settings/company/'
    | '/app/$workspaceSlug/settings/rota/'
    | '/app/$workspaceSlug/settings/team/'
    | '/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'
    | '/app/$workspaceSlug/rota/$locationSlug/$rotaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clock'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/admin/clock-tags'
    | '/clock/$token'
    | '/features/rota-planning'
    | '/features/time-tracking'
    | '/features/timesheets'
    | '/help/$'
    | '/join/$token'
    | '/help'
    | '/account'
    | '/dashboard'
    | '/api/admin-telemetry/error'
    | '/api/admin-telemetry/event'
    | '/api/auth/$'
    | '/api/billing/reconcile'
    | '/api/stripe/webhook'
    | '/api/support/thread'
    | '/billing/expired'
    | '/billing/success'
    | '/onboarding/invite'
    | '/onboarding/join'
    | '/onboarding/location'
    | '/onboarding/org'
    | '/onboarding/setup'
    | '/w/$'
    | '/api/auth/stripe/webhook'
    | '/w'
    | '/app/$workspaceSlug/account'
    | '/app/$workspaceSlug/announcements'
    | '/app/$workspaceSlug/dashboard'
    | '/app/$workspaceSlug/shift-swaps'
    | '/app/$workspaceSlug/time-clock'
    | '/app/$workspaceSlug/timesheets'
    | '/app/$workspaceSlug'
    | '/app/$workspaceSlug/settings/billing'
    | '/app/$workspaceSlug/settings/clocking'
    | '/app/$workspaceSlug/settings/connections'
    | '/app/$workspaceSlug/settings/general'
    | '/app/$workspaceSlug/settings/locations'
    | '/app/$workspaceSlug/rota'
    | '/app/$workspaceSlug/settings'
    | '/app/$workspaceSlug/settings/company/$employeeId'
    | '/app/$workspaceSlug/settings/rota/zones'
    | '/app/$workspaceSlug/settings/team/groups'
    | '/o/$orgSlug/rota/$locationSlug/$rotaId'
    | '/app/$workspaceSlug/settings/company'
    | '/app/$workspaceSlug/settings/rota'
    | '/app/$workspaceSlug/settings/team'
    | '/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'
    | '/app/$workspaceSlug/rota/$locationSlug/$rotaId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/clock'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/_authed/_verified'
    | '/accept-invitation/$invitationId'
    | '/admin/clock-tags'
    | '/clock/$token'
    | '/features/rota-planning'
    | '/features/time-tracking'
    | '/features/timesheets'
    | '/help/$'
    | '/join/$token'
    | '/help/'
    | '/_authed/_verified/account'
    | '/_authed/_verified/dashboard'
    | '/api/admin-telemetry/error'
    | '/api/admin-telemetry/event'
    | '/api/auth/$'
    | '/api/billing/reconcile'
    | '/api/stripe/webhook'
    | '/api/support/thread'
    | '/_authed/_verified/app/$workspaceSlug'
    | '/_authed/_verified/billing/expired'
    | '/_authed/_verified/billing/success'
    | '/_authed/_verified/onboarding/invite'
    | '/_authed/_verified/onboarding/join'
    | '/_authed/_verified/onboarding/location'
    | '/_authed/_verified/onboarding/org'
    | '/_authed/_verified/onboarding/setup'
    | '/_authed/_verified/w/$'
    | '/api/auth/stripe/webhook'
    | '/_authed/_verified/w/'
    | '/_authed/_verified/app/$workspaceSlug/account'
    | '/_authed/_verified/app/$workspaceSlug/announcements'
    | '/_authed/_verified/app/$workspaceSlug/dashboard'
    | '/_authed/_verified/app/$workspaceSlug/settings'
    | '/_authed/_verified/app/$workspaceSlug/shift-swaps'
    | '/_authed/_verified/app/$workspaceSlug/time-clock'
    | '/_authed/_verified/app/$workspaceSlug/timesheets'
    | '/_authed/_verified/app/$workspaceSlug/'
    | '/_authed/_verified/app/$workspaceSlug/settings/billing'
    | '/_authed/_verified/app/$workspaceSlug/settings/clocking'
    | '/_authed/_verified/app/$workspaceSlug/settings/company'
    | '/_authed/_verified/app/$workspaceSlug/settings/connections'
    | '/_authed/_verified/app/$workspaceSlug/settings/general'
    | '/_authed/_verified/app/$workspaceSlug/settings/locations'
    | '/_authed/_verified/app/$workspaceSlug/settings/rota'
    | '/_authed/_verified/app/$workspaceSlug/settings/team'
    | '/_authed/_verified/app/$workspaceSlug/rota/'
    | '/_authed/_verified/app/$workspaceSlug/settings/'
    | '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId'
    | '/_authed/_verified/app/$workspaceSlug/settings/company/$employeeId'
    | '/_authed/_verified/app/$workspaceSlug/settings/rota/zones'
    | '/_authed/_verified/app/$workspaceSlug/settings/team/groups'
    | '/_authed/_verified/o/$orgSlug/rota/$locationSlug/$rotaId'
    | '/_authed/_verified/app/$workspaceSlug/settings/company/'
    | '/_authed/_verified/app/$workspaceSlug/settings/rota/'
    | '/_authed/_verified/app/$workspaceSlug/settings/team/'
    | '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'
    | '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ClockRoute: typeof ClockRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AdminClockTagsRoute: typeof AdminClockTagsRoute
  FeaturesRotaPlanningRoute: typeof FeaturesRotaPlanningRoute
  FeaturesTimeTrackingRoute: typeof FeaturesTimeTrackingRoute
  FeaturesTimesheetsRoute: typeof FeaturesTimesheetsRoute
  HelpSplatRoute: typeof HelpSplatRoute
  JoinTokenRoute: typeof JoinTokenRoute
  HelpIndexRoute: typeof HelpIndexRoute
  ApiAdminTelemetryErrorRoute: typeof ApiAdminTelemetryErrorRoute
  ApiAdminTelemetryEventRoute: typeof ApiAdminTelemetryEventRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingReconcileRoute: typeof ApiBillingReconcileRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSupportThreadRoute: typeof ApiSupportThreadRoute
  ApiAuthStripeWebhookRoute: typeof ApiAuthStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$': {
      id: '/help/$'
      path: '/help/$'
      fullPath: '/help/$'
      preLoaderRoute: typeof HelpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/timesheets': {
      id: '/features/timesheets'
      path: '/features/timesheets'
      fullPath: '/features/timesheets'
      preLoaderRoute: typeof FeaturesTimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/time-tracking': {
      id: '/features/time-tracking'
      path: '/features/time-tracking'
      fullPath: '/features/time-tracking'
      preLoaderRoute: typeof FeaturesTimeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/rota-planning': {
      id: '/features/rota-planning'
      path: '/features/rota-planning'
      fullPath: '/features/rota-planning'
      preLoaderRoute: typeof FeaturesRotaPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock/$token': {
      id: '/clock/$token'
      path: '/$token'
      fullPath: '/clock/$token'
      preLoaderRoute: typeof ClockTokenRouteImport
      parentRoute: typeof ClockRoute
    }
    '/admin/clock-tags': {
      id: '/admin/clock-tags'
      path: '/admin/clock-tags'
      fullPath: '/admin/clock-tags'
      preLoaderRoute: typeof AdminClockTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_verified': {
      id: '/_authed/_verified'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedVerifiedRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/support/thread': {
      id: '/api/support/thread'
      path: '/api/support/thread'
      fullPath: '/api/support/thread'
      preLoaderRoute: typeof ApiSupportThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/reconcile': {
      id: '/api/billing/reconcile'
      path: '/api/billing/reconcile'
      fullPath: '/api/billing/reconcile'
      preLoaderRoute: typeof ApiBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-telemetry/event': {
      id: '/api/admin-telemetry/event'
      path: '/api/admin-telemetry/event'
      fullPath: '/api/admin-telemetry/event'
      preLoaderRoute: typeof ApiAdminTelemetryEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-telemetry/error': {
      id: '/api/admin-telemetry/error'
      path: '/api/admin-telemetry/error'
      fullPath: '/api/admin-telemetry/error'
      preLoaderRoute: typeof ApiAdminTelemetryErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_verified/dashboard': {
      id: '/_authed/_verified/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedVerifiedDashboardRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/account': {
      id: '/_authed/_verified/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedVerifiedAccountRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/w/': {
      id: '/_authed/_verified/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof AuthedVerifiedWIndexRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/api/auth/stripe/webhook': {
      id: '/api/auth/stripe/webhook'
      path: '/api/auth/stripe/webhook'
      fullPath: '/api/auth/stripe/webhook'
      preLoaderRoute: typeof ApiAuthStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_verified/w/$': {
      id: '/_authed/_verified/w/$'
      path: '/w/$'
      fullPath: '/w/$'
      preLoaderRoute: typeof AuthedVerifiedWSplatRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/onboarding/setup': {
      id: '/_authed/_verified/onboarding/setup'
      path: '/onboarding/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof AuthedVerifiedOnboardingSetupRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/onboarding/org': {
      id: '/_authed/_verified/onboarding/org'
      path: '/onboarding/org'
      fullPath: '/onboarding/org'
      preLoaderRoute: typeof AuthedVerifiedOnboardingOrgRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/onboarding/location': {
      id: '/_authed/_verified/onboarding/location'
      path: '/onboarding/location'
      fullPath: '/onboarding/location'
      preLoaderRoute: typeof AuthedVerifiedOnboardingLocationRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/onboarding/join': {
      id: '/_authed/_verified/onboarding/join'
      path: '/onboarding/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof AuthedVerifiedOnboardingJoinRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/onboarding/invite': {
      id: '/_authed/_verified/onboarding/invite'
      path: '/onboarding/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof AuthedVerifiedOnboardingInviteRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/billing/success': {
      id: '/_authed/_verified/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof AuthedVerifiedBillingSuccessRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/billing/expired': {
      id: '/_authed/_verified/billing/expired'
      path: '/billing/expired'
      fullPath: '/billing/expired'
      preLoaderRoute: typeof AuthedVerifiedBillingExpiredRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug': {
      id: '/_authed/_verified/app/$workspaceSlug'
      path: '/app/$workspaceSlug'
      fullPath: '/app/$workspaceSlug'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/': {
      id: '/_authed/_verified/app/$workspaceSlug/'
      path: '/'
      fullPath: '/app/$workspaceSlug/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/timesheets': {
      id: '/_authed/_verified/app/$workspaceSlug/timesheets'
      path: '/timesheets'
      fullPath: '/app/$workspaceSlug/timesheets'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugTimesheetsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/time-clock': {
      id: '/_authed/_verified/app/$workspaceSlug/time-clock'
      path: '/time-clock'
      fullPath: '/app/$workspaceSlug/time-clock'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugTimeClockRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/shift-swaps': {
      id: '/_authed/_verified/app/$workspaceSlug/shift-swaps'
      path: '/shift-swaps'
      fullPath: '/app/$workspaceSlug/shift-swaps'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugShiftSwapsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings': {
      id: '/_authed/_verified/app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/app/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/dashboard': {
      id: '/_authed/_verified/app/$workspaceSlug/dashboard'
      path: '/dashboard'
      fullPath: '/app/$workspaceSlug/dashboard'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugDashboardRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/announcements': {
      id: '/_authed/_verified/app/$workspaceSlug/announcements'
      path: '/announcements'
      fullPath: '/app/$workspaceSlug/announcements'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugAnnouncementsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/account': {
      id: '/_authed/_verified/app/$workspaceSlug/account'
      path: '/account'
      fullPath: '/app/$workspaceSlug/account'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugAccountRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/'
      path: '/'
      fullPath: '/app/$workspaceSlug/settings/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/rota/': {
      id: '/_authed/_verified/app/$workspaceSlug/rota/'
      path: '/rota'
      fullPath: '/app/$workspaceSlug/rota/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/team': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/team'
      path: '/team'
      fullPath: '/app/$workspaceSlug/settings/team'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/rota': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/rota'
      path: '/rota'
      fullPath: '/app/$workspaceSlug/settings/rota'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/locations': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/locations'
      path: '/locations'
      fullPath: '/app/$workspaceSlug/settings/locations'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsLocationsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/general': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/general'
      path: '/general'
      fullPath: '/app/$workspaceSlug/settings/general'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/connections': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/connections'
      path: '/connections'
      fullPath: '/app/$workspaceSlug/settings/connections'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/company': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/company'
      path: '/company'
      fullPath: '/app/$workspaceSlug/settings/company'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/clocking': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/clocking'
      path: '/clocking'
      fullPath: '/app/$workspaceSlug/settings/clocking'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsClockingRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/billing': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/billing'
      path: '/billing'
      fullPath: '/app/$workspaceSlug/settings/billing'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsBillingRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/team/': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/team/'
      path: '/'
      fullPath: '/app/$workspaceSlug/settings/team/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/rota/': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/rota/'
      path: '/'
      fullPath: '/app/$workspaceSlug/settings/rota/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/company/': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/company/'
      path: '/'
      fullPath: '/app/$workspaceSlug/settings/company/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute
    }
    '/_authed/_verified/o/$orgSlug/rota/$locationSlug/$rotaId': {
      id: '/_authed/_verified/o/$orgSlug/rota/$locationSlug/$rotaId'
      path: '/o/$orgSlug/rota/$locationSlug/$rotaId'
      fullPath: '/o/$orgSlug/rota/$locationSlug/$rotaId'
      preLoaderRoute: typeof AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRouteImport
      parentRoute: typeof AuthedVerifiedRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/team/groups': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/team/groups'
      path: '/groups'
      fullPath: '/app/$workspaceSlug/settings/team/groups'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/rota/zones': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/rota/zones'
      path: '/zones'
      fullPath: '/app/$workspaceSlug/settings/rota/zones'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute
    }
    '/_authed/_verified/app/$workspaceSlug/settings/company/$employeeId': {
      id: '/_authed/_verified/app/$workspaceSlug/settings/company/$employeeId'
      path: '/$employeeId'
      fullPath: '/app/$workspaceSlug/settings/company/$employeeId'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute
    }
    '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId': {
      id: '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId'
      path: '/rota/$locationSlug/$rotaId'
      fullPath: '/app/$workspaceSlug/rota/$locationSlug/$rotaId'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRoute
    }
    '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/': {
      id: '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/'
      path: '/'
      fullPath: '/app/$workspaceSlug/rota/$locationSlug/$rotaId/'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute
    }
    '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/view': {
      id: '/_authed/_verified/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'
      path: '/view'
      fullPath: '/app/$workspaceSlug/rota/$locationSlug/$rotaId/view'
      preLoaderRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRouteImport
      parentRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute
    }
  }
}

interface AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteChildren {
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute
}

const AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteChildren: AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsCompanyEmployeeIdRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsCompanyIndexRoute,
  }

const AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteChildren,
  )

interface AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteChildren {
  AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute
  AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute
}

const AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteChildren: AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsRotaZonesRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsRotaIndexRoute,
  }

const AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteChildren,
  )

interface AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteChildren {
  AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute
  AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute
}

const AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteChildren: AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsTeamGroupsRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsTeamIndexRoute,
  }

const AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteChildren,
  )

interface AuthedVerifiedAppWorkspaceSlugSettingsRouteChildren {
  AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute
  AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute
  AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteWithChildren
  AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute
  AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute
  AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute
  AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteWithChildren
  AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteWithChildren
  AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute
}

const AuthedVerifiedAppWorkspaceSlugSettingsRouteChildren: AuthedVerifiedAppWorkspaceSlugSettingsRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsBillingRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsClockingRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsCompanyRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsCompanyRouteWithChildren,
    AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsConnectionsRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsGeneralRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsLocationsRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsRotaRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsRotaRouteWithChildren,
    AuthedVerifiedAppWorkspaceSlugSettingsTeamRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsTeamRouteWithChildren,
    AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsIndexRoute,
  }

const AuthedVerifiedAppWorkspaceSlugSettingsRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugSettingsRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugSettingsRouteChildren,
  )

interface AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteChildren {
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute
}

const AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteChildren: AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute:
      AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdViewRoute,
    AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute:
      AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdIndexRoute,
  }

const AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteChildren,
  )

interface AuthedVerifiedAppWorkspaceSlugRouteRouteChildren {
  AuthedVerifiedAppWorkspaceSlugAccountRoute: typeof AuthedVerifiedAppWorkspaceSlugAccountRoute
  AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute: typeof AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute
  AuthedVerifiedAppWorkspaceSlugDashboardRoute: typeof AuthedVerifiedAppWorkspaceSlugDashboardRoute
  AuthedVerifiedAppWorkspaceSlugSettingsRoute: typeof AuthedVerifiedAppWorkspaceSlugSettingsRouteWithChildren
  AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute: typeof AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute
  AuthedVerifiedAppWorkspaceSlugTimeClockRoute: typeof AuthedVerifiedAppWorkspaceSlugTimeClockRoute
  AuthedVerifiedAppWorkspaceSlugTimesheetsRoute: typeof AuthedVerifiedAppWorkspaceSlugTimesheetsRoute
  AuthedVerifiedAppWorkspaceSlugIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugIndexRoute
  AuthedVerifiedAppWorkspaceSlugRotaIndexRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaIndexRoute
  AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute: typeof AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteWithChildren
}

const AuthedVerifiedAppWorkspaceSlugRouteRouteChildren: AuthedVerifiedAppWorkspaceSlugRouteRouteChildren =
  {
    AuthedVerifiedAppWorkspaceSlugAccountRoute:
      AuthedVerifiedAppWorkspaceSlugAccountRoute,
    AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute:
      AuthedVerifiedAppWorkspaceSlugAnnouncementsRoute,
    AuthedVerifiedAppWorkspaceSlugDashboardRoute:
      AuthedVerifiedAppWorkspaceSlugDashboardRoute,
    AuthedVerifiedAppWorkspaceSlugSettingsRoute:
      AuthedVerifiedAppWorkspaceSlugSettingsRouteWithChildren,
    AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute:
      AuthedVerifiedAppWorkspaceSlugShiftSwapsRoute,
    AuthedVerifiedAppWorkspaceSlugTimeClockRoute:
      AuthedVerifiedAppWorkspaceSlugTimeClockRoute,
    AuthedVerifiedAppWorkspaceSlugTimesheetsRoute:
      AuthedVerifiedAppWorkspaceSlugTimesheetsRoute,
    AuthedVerifiedAppWorkspaceSlugIndexRoute:
      AuthedVerifiedAppWorkspaceSlugIndexRoute,
    AuthedVerifiedAppWorkspaceSlugRotaIndexRoute:
      AuthedVerifiedAppWorkspaceSlugRotaIndexRoute,
    AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRoute:
      AuthedVerifiedAppWorkspaceSlugRotaLocationSlugRotaIdRouteWithChildren,
  }

const AuthedVerifiedAppWorkspaceSlugRouteRouteWithChildren =
  AuthedVerifiedAppWorkspaceSlugRouteRoute._addFileChildren(
    AuthedVerifiedAppWorkspaceSlugRouteRouteChildren,
  )

interface AuthedVerifiedRouteRouteChildren {
  AuthedVerifiedAccountRoute: typeof AuthedVerifiedAccountRoute
  AuthedVerifiedDashboardRoute: typeof AuthedVerifiedDashboardRoute
  AuthedVerifiedAppWorkspaceSlugRouteRoute: typeof AuthedVerifiedAppWorkspaceSlugRouteRouteWithChildren
  AuthedVerifiedBillingExpiredRoute: typeof AuthedVerifiedBillingExpiredRoute
  AuthedVerifiedBillingSuccessRoute: typeof AuthedVerifiedBillingSuccessRoute
  AuthedVerifiedOnboardingInviteRoute: typeof AuthedVerifiedOnboardingInviteRoute
  AuthedVerifiedOnboardingJoinRoute: typeof AuthedVerifiedOnboardingJoinRoute
  AuthedVerifiedOnboardingLocationRoute: typeof AuthedVerifiedOnboardingLocationRoute
  AuthedVerifiedOnboardingOrgRoute: typeof AuthedVerifiedOnboardingOrgRoute
  AuthedVerifiedOnboardingSetupRoute: typeof AuthedVerifiedOnboardingSetupRoute
  AuthedVerifiedWSplatRoute: typeof AuthedVerifiedWSplatRoute
  AuthedVerifiedWIndexRoute: typeof AuthedVerifiedWIndexRoute
  AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute: typeof AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute
}

const AuthedVerifiedRouteRouteChildren: AuthedVerifiedRouteRouteChildren = {
  AuthedVerifiedAccountRoute: AuthedVerifiedAccountRoute,
  AuthedVerifiedDashboardRoute: AuthedVerifiedDashboardRoute,
  AuthedVerifiedAppWorkspaceSlugRouteRoute:
    AuthedVerifiedAppWorkspaceSlugRouteRouteWithChildren,
  AuthedVerifiedBillingExpiredRoute: AuthedVerifiedBillingExpiredRoute,
  AuthedVerifiedBillingSuccessRoute: AuthedVerifiedBillingSuccessRoute,
  AuthedVerifiedOnboardingInviteRoute: AuthedVerifiedOnboardingInviteRoute,
  AuthedVerifiedOnboardingJoinRoute: AuthedVerifiedOnboardingJoinRoute,
  AuthedVerifiedOnboardingLocationRoute: AuthedVerifiedOnboardingLocationRoute,
  AuthedVerifiedOnboardingOrgRoute: AuthedVerifiedOnboardingOrgRoute,
  AuthedVerifiedOnboardingSetupRoute: AuthedVerifiedOnboardingSetupRoute,
  AuthedVerifiedWSplatRoute: AuthedVerifiedWSplatRoute,
  AuthedVerifiedWIndexRoute: AuthedVerifiedWIndexRoute,
  AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute:
    AuthedVerifiedOOrgSlugRotaLocationSlugRotaIdRoute,
}

const AuthedVerifiedRouteRouteWithChildren =
  AuthedVerifiedRouteRoute._addFileChildren(AuthedVerifiedRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedVerifiedRouteRoute: typeof AuthedVerifiedRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedVerifiedRouteRoute: AuthedVerifiedRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface ClockRouteChildren {
  ClockTokenRoute: typeof ClockTokenRoute
}

const ClockRouteChildren: ClockRouteChildren = {
  ClockTokenRoute: ClockTokenRoute,
}

const ClockRouteWithChildren = ClockRoute._addFileChildren(ClockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ClockRoute: ClockRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AdminClockTagsRoute: AdminClockTagsRoute,
  FeaturesRotaPlanningRoute: FeaturesRotaPlanningRoute,
  FeaturesTimeTrackingRoute: FeaturesTimeTrackingRoute,
  FeaturesTimesheetsRoute: FeaturesTimesheetsRoute,
  HelpSplatRoute: HelpSplatRoute,
  JoinTokenRoute: JoinTokenRoute,
  HelpIndexRoute: HelpIndexRoute,
  ApiAdminTelemetryErrorRoute: ApiAdminTelemetryErrorRoute,
  ApiAdminTelemetryEventRoute: ApiAdminTelemetryEventRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingReconcileRoute: ApiBillingReconcileRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSupportThreadRoute: ApiSupportThreadRoute,
  ApiAuthStripeWebhookRoute: ApiAuthStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
