alter table admin_private.support_messages
  add column message_number bigint generated by default as identity;

with ordered_messages as (
  select id, row_number() over (order by created_at, id) as message_number
  from admin_private.support_messages
)
update admin_private.support_messages message
set message_number = ordered_messages.message_number
from ordered_messages
where message.id = ordered_messages.id;

select setval(
  pg_get_serial_sequence('admin_private.support_messages', 'message_number'),
  coalesce(max(message_number), 1),
  count(*) > 0
)
from admin_private.support_messages;

alter table admin_private.support_messages
  alter column message_number set generated always;

create index support_messages_thread_number_idx
  on admin_private.support_messages (thread_id, message_number desc);

create index support_threads_requester_updated_idx
  on admin_private.support_threads
  (organization_id, created_by_user_id, updated_at desc, id desc);

create index support_threads_updated_idx
  on admin_private.support_threads (updated_at desc, id desc);

create table admin_private.support_thread_reads (
  thread_id uuid not null references admin_private.support_threads(id) on delete cascade,
  reader_kind text not null check (reader_kind in ('user', 'admin')),
  reader_id text not null,
  last_read_message_number bigint not null default 0,
  primary key (thread_id, reader_kind, reader_id)
);

alter table admin_private.support_thread_reads enable row level security;
revoke all on admin_private.support_thread_reads from public, anon, authenticated;
grant all on admin_private.support_thread_reads to postgres, service_role;
grant all on all sequences in schema admin_private to postgres, service_role;
